# Generated by Django 5.2 on 2025-05-16 09:42

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("handcrafts", "0003_post_handcraft_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
