# Generated by Django 5.2 on 2025-05-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handcrafts', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on', 'author']},
        ),
    ]
