# Generated by Django 5.2 on 2025-05-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handcrafts", "0006_post_image_alt_post_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="handcraft_type",
            field=models.CharField(
                choices=[
                    ("knitting", "Knitting"),
                    ("crochet", "Crochet"),
                    ("sewing", "Sewing"),
                    ("embroidery", "Embroidery"),
                    ("other", "Other"),
                ],
                default="knitting",
                max_length=50,
            ),
        ),
    ]
