# Generated by Django 5.2 on 2025-06-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("handcrafts", "0008_alter_post_handcraft_type_favorite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="create_on",
            new_name="created_on",
        ),
    ]
