# Generated by Django 5.2 on 2025-06-07 21:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("handcrafts", "0009_rename_create_on_favorite_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="handcrafts_defaults/default_sewing_card",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
