# Generated by Django 5.2 on 2025-06-07 23:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("handcrafts", "0011_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="handcrafts_defaults/default_sewing_card",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
